// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"mesa-ads/internal/core/domain"
	"mesa-ads/internal/core/port"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockAdRepository creates a new instance of MockAdRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAdRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAdRepository {
	mock := &MockAdRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAdRepository is an autogenerated mock type for the AdRepository type
type MockAdRepository struct {
	mock.Mock
}

type MockAdRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAdRepository) EXPECT() *MockAdRepository_Expecter {
	return &MockAdRepository_Expecter{mock: &_m.Mock}
}

// CreateClickAndDeductBudget provides a mock function for the type MockAdRepository
func (_mock *MockAdRepository) CreateClickAndDeductBudget(ctx context.Context, click *domain.Click, cpcBid int64) error {
	ret := _mock.Called(ctx, click, cpcBid)

	if len(ret) == 0 {
		panic("no return value specified for CreateClickAndDeductBudget")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Click, int64) error); ok {
		r0 = returnFunc(ctx, click, cpcBid)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAdRepository_CreateClickAndDeductBudget_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateClickAndDeductBudget'
type MockAdRepository_CreateClickAndDeductBudget_Call struct {
	*mock.Call
}

// CreateClickAndDeductBudget is a helper method to define mock.On call
//   - ctx
//   - click
//   - cpcBid
func (_e *MockAdRepository_Expecter) CreateClickAndDeductBudget(ctx interface{}, click interface{}, cpcBid interface{}) *MockAdRepository_CreateClickAndDeductBudget_Call {
	return &MockAdRepository_CreateClickAndDeductBudget_Call{Call: _e.mock.On("CreateClickAndDeductBudget", ctx, click, cpcBid)}
}

func (_c *MockAdRepository_CreateClickAndDeductBudget_Call) Run(run func(ctx context.Context, click *domain.Click, cpcBid int64)) *MockAdRepository_CreateClickAndDeductBudget_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Click), args[2].(int64))
	})
	return _c
}

func (_c *MockAdRepository_CreateClickAndDeductBudget_Call) Return(err error) *MockAdRepository_CreateClickAndDeductBudget_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAdRepository_CreateClickAndDeductBudget_Call) RunAndReturn(run func(ctx context.Context, click *domain.Click, cpcBid int64) error) *MockAdRepository_CreateClickAndDeductBudget_Call {
	_c.Call.Return(run)
	return _c
}

// CreateImpressionAndDeductBudget provides a mock function for the type MockAdRepository
func (_mock *MockAdRepository) CreateImpressionAndDeductBudget(ctx context.Context, imp *domain.Impression, cpmBid int64) error {
	ret := _mock.Called(ctx, imp, cpmBid)

	if len(ret) == 0 {
		panic("no return value specified for CreateImpressionAndDeductBudget")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Impression, int64) error); ok {
		r0 = returnFunc(ctx, imp, cpmBid)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAdRepository_CreateImpressionAndDeductBudget_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateImpressionAndDeductBudget'
type MockAdRepository_CreateImpressionAndDeductBudget_Call struct {
	*mock.Call
}

// CreateImpressionAndDeductBudget is a helper method to define mock.On call
//   - ctx
//   - imp
//   - cpmBid
func (_e *MockAdRepository_Expecter) CreateImpressionAndDeductBudget(ctx interface{}, imp interface{}, cpmBid interface{}) *MockAdRepository_CreateImpressionAndDeductBudget_Call {
	return &MockAdRepository_CreateImpressionAndDeductBudget_Call{Call: _e.mock.On("CreateImpressionAndDeductBudget", ctx, imp, cpmBid)}
}

func (_c *MockAdRepository_CreateImpressionAndDeductBudget_Call) Run(run func(ctx context.Context, imp *domain.Impression, cpmBid int64)) *MockAdRepository_CreateImpressionAndDeductBudget_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Impression), args[2].(int64))
	})
	return _c
}

func (_c *MockAdRepository_CreateImpressionAndDeductBudget_Call) Return(err error) *MockAdRepository_CreateImpressionAndDeductBudget_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAdRepository_CreateImpressionAndDeductBudget_Call) RunAndReturn(run func(ctx context.Context, imp *domain.Impression, cpmBid int64) error) *MockAdRepository_CreateImpressionAndDeductBudget_Call {
	_c.Call.Return(run)
	return _c
}

// FindImpressionByToken provides a mock function for the type MockAdRepository
func (_mock *MockAdRepository) FindImpressionByToken(ctx context.Context, token string) (*domain.Impression, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for FindImpressionByToken")
	}

	var r0 *domain.Impression
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Impression, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Impression); ok {
		r0 = returnFunc(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Impression)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdRepository_FindImpressionByToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindImpressionByToken'
type MockAdRepository_FindImpressionByToken_Call struct {
	*mock.Call
}

// FindImpressionByToken is a helper method to define mock.On call
//   - ctx
//   - token
func (_e *MockAdRepository_Expecter) FindImpressionByToken(ctx interface{}, token interface{}) *MockAdRepository_FindImpressionByToken_Call {
	return &MockAdRepository_FindImpressionByToken_Call{Call: _e.mock.On("FindImpressionByToken", ctx, token)}
}

func (_c *MockAdRepository_FindImpressionByToken_Call) Run(run func(ctx context.Context, token string)) *MockAdRepository_FindImpressionByToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAdRepository_FindImpressionByToken_Call) Return(impression *domain.Impression, err error) *MockAdRepository_FindImpressionByToken_Call {
	_c.Call.Return(impression, err)
	return _c
}

func (_c *MockAdRepository_FindImpressionByToken_Call) RunAndReturn(run func(ctx context.Context, token string) (*domain.Impression, error)) *MockAdRepository_FindImpressionByToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetCampaign provides a mock function for the type MockAdRepository
func (_mock *MockAdRepository) GetCampaign(ctx context.Context, id int64) (*domain.Campaign, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetCampaign")
	}

	var r0 *domain.Campaign
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*domain.Campaign, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *domain.Campaign); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Campaign)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdRepository_GetCampaign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCampaign'
type MockAdRepository_GetCampaign_Call struct {
	*mock.Call
}

// GetCampaign is a helper method to define mock.On call
//   - ctx
//   - id
func (_e *MockAdRepository_Expecter) GetCampaign(ctx interface{}, id interface{}) *MockAdRepository_GetCampaign_Call {
	return &MockAdRepository_GetCampaign_Call{Call: _e.mock.On("GetCampaign", ctx, id)}
}

func (_c *MockAdRepository_GetCampaign_Call) Run(run func(ctx context.Context, id int64)) *MockAdRepository_GetCampaign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockAdRepository_GetCampaign_Call) Return(campaign *domain.Campaign, err error) *MockAdRepository_GetCampaign_Call {
	_c.Call.Return(campaign, err)
	return _c
}

func (_c *MockAdRepository_GetCampaign_Call) RunAndReturn(run func(ctx context.Context, id int64) (*domain.Campaign, error)) *MockAdRepository_GetCampaign_Call {
	_c.Call.Return(run)
	return _c
}

// GetCreative provides a mock function for the type MockAdRepository
func (_mock *MockAdRepository) GetCreative(ctx context.Context, id int64) (*domain.Creative, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetCreative")
	}

	var r0 *domain.Creative
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*domain.Creative, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *domain.Creative); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Creative)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdRepository_GetCreative_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCreative'
type MockAdRepository_GetCreative_Call struct {
	*mock.Call
}

// GetCreative is a helper method to define mock.On call
//   - ctx
//   - id
func (_e *MockAdRepository_Expecter) GetCreative(ctx interface{}, id interface{}) *MockAdRepository_GetCreative_Call {
	return &MockAdRepository_GetCreative_Call{Call: _e.mock.On("GetCreative", ctx, id)}
}

func (_c *MockAdRepository_GetCreative_Call) Run(run func(ctx context.Context, id int64)) *MockAdRepository_GetCreative_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockAdRepository_GetCreative_Call) Return(creative *domain.Creative, err error) *MockAdRepository_GetCreative_Call {
	_c.Call.Return(creative, err)
	return _c
}

func (_c *MockAdRepository_GetCreative_Call) RunAndReturn(run func(ctx context.Context, id int64) (*domain.Creative, error)) *MockAdRepository_GetCreative_Call {
	_c.Call.Return(run)
	return _c
}

// GetEligibleCreatives provides a mock function for the type MockAdRepository
func (_mock *MockAdRepository) GetEligibleCreatives(ctx context.Context, user domain.UserContext) ([]port.CreativeCandidate, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for GetEligibleCreatives")
	}

	var r0 []port.CreativeCandidate
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserContext) ([]port.CreativeCandidate, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserContext) []port.CreativeCandidate); ok {
		r0 = returnFunc(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]port.CreativeCandidate)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.UserContext) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdRepository_GetEligibleCreatives_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEligibleCreatives'
type MockAdRepository_GetEligibleCreatives_Call struct {
	*mock.Call
}

// GetEligibleCreatives is a helper method to define mock.On call
//   - ctx
//   - user
func (_e *MockAdRepository_Expecter) GetEligibleCreatives(ctx interface{}, user interface{}) *MockAdRepository_GetEligibleCreatives_Call {
	return &MockAdRepository_GetEligibleCreatives_Call{Call: _e.mock.On("GetEligibleCreatives", ctx, user)}
}

func (_c *MockAdRepository_GetEligibleCreatives_Call) Run(run func(ctx context.Context, user domain.UserContext)) *MockAdRepository_GetEligibleCreatives_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.UserContext))
	})
	return _c
}

func (_c *MockAdRepository_GetEligibleCreatives_Call) Return(creativeCandidates []port.CreativeCandidate, err error) *MockAdRepository_GetEligibleCreatives_Call {
	_c.Call.Return(creativeCandidates, err)
	return _c
}

func (_c *MockAdRepository_GetEligibleCreatives_Call) RunAndReturn(run func(ctx context.Context, user domain.UserContext) ([]port.CreativeCandidate, error)) *MockAdRepository_GetEligibleCreatives_Call {
	_c.Call.Return(run)
	return _c
}

// GetStats provides a mock function for the type MockAdRepository
func (_mock *MockAdRepository) GetStats(ctx context.Context, from time.Time, to time.Time, campaignID *int64) (*port.StatsResp, error) {
	ret := _mock.Called(ctx, from, to, campaignID)

	if len(ret) == 0 {
		panic("no return value specified for GetStats")
	}

	var r0 *port.StatsResp
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, time.Time, *int64) (*port.StatsResp, error)); ok {
		return returnFunc(ctx, from, to, campaignID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, time.Time, *int64) *port.StatsResp); ok {
		r0 = returnFunc(ctx, from, to, campaignID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*port.StatsResp)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Time, time.Time, *int64) error); ok {
		r1 = returnFunc(ctx, from, to, campaignID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdRepository_GetStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStats'
type MockAdRepository_GetStats_Call struct {
	*mock.Call
}

// GetStats is a helper method to define mock.On call
//   - ctx
//   - from
//   - to
//   - campaignID
func (_e *MockAdRepository_Expecter) GetStats(ctx interface{}, from interface{}, to interface{}, campaignID interface{}) *MockAdRepository_GetStats_Call {
	return &MockAdRepository_GetStats_Call{Call: _e.mock.On("GetStats", ctx, from, to, campaignID)}
}

func (_c *MockAdRepository_GetStats_Call) Run(run func(ctx context.Context, from time.Time, to time.Time, campaignID *int64)) *MockAdRepository_GetStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time), args[2].(time.Time), args[3].(*int64))
	})
	return _c
}

func (_c *MockAdRepository_GetStats_Call) Return(stats *port.StatsResp, err error) *MockAdRepository_GetStats_Call {
	_c.Call.Return(stats, err)
	return _c
}

func (_c *MockAdRepository_GetStats_Call) RunAndReturn(run func(ctx context.Context, from time.Time, to time.Time, campaignID *int64) (*port.StatsResp, error)) *MockAdRepository_GetStats_Call {
	_c.Call.Return(run)
	return _c
}
