// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"mesa-ads/internal/core/domain"
	"mesa-ads/internal/core/port"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockAdService creates a new instance of MockAdService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAdService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAdService {
	mock := &MockAdService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAdService is an autogenerated mock type for the AdUseCase type
type MockAdService struct {
	mock.Mock
}

type MockAdService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAdService) EXPECT() *MockAdService_Expecter {
	return &MockAdService_Expecter{mock: &_m.Mock}
}

// GetStats provides a mock function for the type MockAdService
func (_mock *MockAdService) GetStats(ctx context.Context, from time.Time, to time.Time, campaignID *int64) (*port.StatsResp, error) {
	ret := _mock.Called(ctx, from, to, campaignID)

	if len(ret) == 0 {
		panic("no return value specified for GetStats")
	}

	var r0 *port.StatsResp
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, time.Time, *int64) (*port.StatsResp, error)); ok {
		return returnFunc(ctx, from, to, campaignID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, time.Time, *int64) *port.StatsResp); ok {
		r0 = returnFunc(ctx, from, to, campaignID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*port.StatsResp)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Time, time.Time, *int64) error); ok {
		r1 = returnFunc(ctx, from, to, campaignID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdService_GetStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStats'
type MockAdService_GetStats_Call struct {
	*mock.Call
}

// GetStats is a helper method to define mock.On call
//   - ctx
//   - from
//   - to
//   - campaignID
func (_e *MockAdService_Expecter) GetStats(ctx interface{}, from interface{}, to interface{}, campaignID interface{}) *MockAdService_GetStats_Call {
	return &MockAdService_GetStats_Call{Call: _e.mock.On("GetStats", ctx, from, to, campaignID)}
}

func (_c *MockAdService_GetStats_Call) Run(run func(ctx context.Context, from time.Time, to time.Time, campaignID *int64)) *MockAdService_GetStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time), args[2].(time.Time), args[3].(*int64))
	})
	return _c
}

func (_c *MockAdService_GetStats_Call) Return(stats *port.StatsResp, err error) *MockAdService_GetStats_Call {
	_c.Call.Return(stats, err)
	return _c
}

func (_c *MockAdService_GetStats_Call) RunAndReturn(run func(ctx context.Context, from time.Time, to time.Time, campaignID *int64) (*port.StatsResp, error)) *MockAdService_GetStats_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterClick provides a mock function for the type MockAdService
func (_mock *MockAdService) RegisterClick(ctx context.Context, token string) (string, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for RegisterClick")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdService_RegisterClick_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterClick'
type MockAdService_RegisterClick_Call struct {
	*mock.Call
}

// RegisterClick is a helper method to define mock.On call
//   - ctx
//   - token
func (_e *MockAdService_Expecter) RegisterClick(ctx interface{}, token interface{}) *MockAdService_RegisterClick_Call {
	return &MockAdService_RegisterClick_Call{Call: _e.mock.On("RegisterClick", ctx, token)}
}

func (_c *MockAdService_RegisterClick_Call) Run(run func(ctx context.Context, token string)) *MockAdService_RegisterClick_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAdService_RegisterClick_Call) Return(s string, err error) *MockAdService_RegisterClick_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockAdService_RegisterClick_Call) RunAndReturn(run func(ctx context.Context, token string) (string, error)) *MockAdService_RegisterClick_Call {
	_c.Call.Return(run)
	return _c
}

// RequestAd provides a mock function for the type MockAdService
func (_mock *MockAdService) RequestAd(ctx context.Context, user domain.UserContext) (*port.AdResponse, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for RequestAd")
	}

	var r0 *port.AdResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserContext) (*port.AdResponse, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserContext) *port.AdResponse); ok {
		r0 = returnFunc(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*port.AdResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.UserContext) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdService_RequestAd_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestAd'
type MockAdService_RequestAd_Call struct {
	*mock.Call
}

// RequestAd is a helper method to define mock.On call
//   - ctx
//   - user
func (_e *MockAdService_Expecter) RequestAd(ctx interface{}, user interface{}) *MockAdService_RequestAd_Call {
	return &MockAdService_RequestAd_Call{Call: _e.mock.On("RequestAd", ctx, user)}
}

func (_c *MockAdService_RequestAd_Call) Run(run func(ctx context.Context, user domain.UserContext)) *MockAdService_RequestAd_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.UserContext))
	})
	return _c
}

func (_c *MockAdService_RequestAd_Call) Return(adResponse *port.AdResponse, err error) *MockAdService_RequestAd_Call {
	_c.Call.Return(adResponse, err)
	return _c
}

func (_c *MockAdService_RequestAd_Call) RunAndReturn(run func(ctx context.Context, user domain.UserContext) (*port.AdResponse, error)) *MockAdService_RequestAd_Call {
	_c.Call.Return(run)
	return _c
}
