// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"mesa-ads/internal/core/domain"
	"mesa-ads/internal/core/port"

	mock "github.com/stretchr/testify/mock"
)

// NewMockAdUseCase creates a new instance of MockAdUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAdUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAdUseCase {
	mock := &MockAdUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAdUseCase is an autogenerated mock type for the AdUseCase type
type MockAdUseCase struct {
	mock.Mock
}

type MockAdUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAdUseCase) EXPECT() *MockAdUseCase_Expecter {
	return &MockAdUseCase_Expecter{mock: &_m.Mock}
}

// GetStats provides a mock function for the type MockAdUseCase
func (_mock *MockAdUseCase) GetStats(ctx context.Context, req port.StatsReq) (*port.StatsResp, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetStats")
	}

	var r0 *port.StatsResp
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, port.StatsReq) (*port.StatsResp, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, port.StatsReq) *port.StatsResp); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*port.StatsResp)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, port.StatsReq) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdUseCase_GetStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStats'
type MockAdUseCase_GetStats_Call struct {
	*mock.Call
}

// GetStats is a helper method to define mock.On call
//   - ctx
//   - req
func (_e *MockAdUseCase_Expecter) GetStats(ctx interface{}, req interface{}) *MockAdUseCase_GetStats_Call {
	return &MockAdUseCase_GetStats_Call{Call: _e.mock.On("GetStats", ctx, req)}
}

func (_c *MockAdUseCase_GetStats_Call) Run(run func(ctx context.Context, req port.StatsReq)) *MockAdUseCase_GetStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(port.StatsReq))
	})
	return _c
}

func (_c *MockAdUseCase_GetStats_Call) Return(statsResp *port.StatsResp, err error) *MockAdUseCase_GetStats_Call {
	_c.Call.Return(statsResp, err)
	return _c
}

func (_c *MockAdUseCase_GetStats_Call) RunAndReturn(run func(ctx context.Context, req port.StatsReq) (*port.StatsResp, error)) *MockAdUseCase_GetStats_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterClick provides a mock function for the type MockAdUseCase
func (_mock *MockAdUseCase) RegisterClick(ctx context.Context, token string) (string, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for RegisterClick")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdUseCase_RegisterClick_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterClick'
type MockAdUseCase_RegisterClick_Call struct {
	*mock.Call
}

// RegisterClick is a helper method to define mock.On call
//   - ctx
//   - token
func (_e *MockAdUseCase_Expecter) RegisterClick(ctx interface{}, token interface{}) *MockAdUseCase_RegisterClick_Call {
	return &MockAdUseCase_RegisterClick_Call{Call: _e.mock.On("RegisterClick", ctx, token)}
}

func (_c *MockAdUseCase_RegisterClick_Call) Run(run func(ctx context.Context, token string)) *MockAdUseCase_RegisterClick_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAdUseCase_RegisterClick_Call) Return(s string, err error) *MockAdUseCase_RegisterClick_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockAdUseCase_RegisterClick_Call) RunAndReturn(run func(ctx context.Context, token string) (string, error)) *MockAdUseCase_RegisterClick_Call {
	_c.Call.Return(run)
	return _c
}

// RequestAd provides a mock function for the type MockAdUseCase
func (_mock *MockAdUseCase) RequestAd(ctx context.Context, user domain.UserContext) (*port.AdResponse, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for RequestAd")
	}

	var r0 *port.AdResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserContext) (*port.AdResponse, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserContext) *port.AdResponse); ok {
		r0 = returnFunc(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*port.AdResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.UserContext) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdUseCase_RequestAd_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestAd'
type MockAdUseCase_RequestAd_Call struct {
	*mock.Call
}

// RequestAd is a helper method to define mock.On call
//   - ctx
//   - user
func (_e *MockAdUseCase_Expecter) RequestAd(ctx interface{}, user interface{}) *MockAdUseCase_RequestAd_Call {
	return &MockAdUseCase_RequestAd_Call{Call: _e.mock.On("RequestAd", ctx, user)}
}

func (_c *MockAdUseCase_RequestAd_Call) Run(run func(ctx context.Context, user domain.UserContext)) *MockAdUseCase_RequestAd_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.UserContext))
	})
	return _c
}

func (_c *MockAdUseCase_RequestAd_Call) Return(adResponse *port.AdResponse, err error) *MockAdUseCase_RequestAd_Call {
	_c.Call.Return(adResponse, err)
	return _c
}

func (_c *MockAdUseCase_RequestAd_Call) RunAndReturn(run func(ctx context.Context, user domain.UserContext) (*port.AdResponse, error)) *MockAdUseCase_RequestAd_Call {
	_c.Call.Return(run)
	return _c
}
